### ISSUE TITLE
Get Date errors

### ISSUE THREAD

**Issue by ghost** [miguelsimoni/hugo-initio#12]
When i run it i get

ERROR 2017/12/25 09:52:11 Error while rendering "page": template: theme/_default/single.html:13:105: executing "theme/_default/single.html" at <.Site.Params.datefor...>: invalid value; expected string
ERROR 2017/12/25 09:52:11 Error while rendering "section": template: theme/_default/list.html:13:104: executing "theme/_default/list.html" at <.Site.Params.datefor...>: invalid value; expected string

Which is this line in list.html

<span class="posted-on"><time class="entry-date published" date="{{ .Date }}">{{ dateFormat .Site.Params.DateForm .Date }}</time></span>

**Comment by miguelsimoni** [comment]
Hi @PurplePilot 

You must have the date format value `dateform` in the params section of the config.toml

```
[params]
    DateForm = "January 2, 2006"
```
