### ISSUE TITLE
How can I change syntax highlighting

### ISSUE THREAD

**Issue by yonkov** [miguelsimoni/hugo-initio#15]
Hi, I really like your theme, but there is something I was not able to configure. I would like to change the default syntax highlighting for code blocks (monokai i think) to another one (manni). How can i implement this? I tried setting the following in my config.toml file, but it did not do the trick.. Thank you very much in advance.

	pygmentsUseClassic=true
	PygmentsCodeFences = true
	PygmentsStyle = "manni"

**Comment by miguelsimoni** [comment]
Hi @yonkov,
I'm not completely familiar with the native highlight of hugo. So, I'm gonna take a look at how it works to give you a solution.

**Comment by gasedwards** [comment]
I'd also like to know how this could be done!

**Comment by gasedwards** [comment]
I figured it out! Or rather I stumbled upon the solution at https://codewithhugo.com/switching-the-lights-on-hugo-vs-hugo-config-files/

The pygments parameters have to be set *before* the [params] line. Then it just works...

**Comment by miguelsimoni** [comment]
Thanks @gasedwards
