### ISSUE TITLE
Images not well positioned

### ISSUE THREAD

**Issue by Lego2012** [miguelsimoni/hugo-initio#2]
At some breakpoints you only see the background of the images and not the content

**Comment by miguelsimoni** [comment]
Hi @Lego2012 
I can't see any issue with images or content. Can you be more specific?
Thanks!

**Comment by Lego2012** [comment]
Yes, sure. Please see attached Screenshot from an iPhone 6 Landscape View.

BTW: Hamburger on iPhone not working?

Regards,
Leo




Leo Merkel

T +49 5286 990 922 | M +49 176 248 248 48

www.confidea.de <http://www.confidea.de/>

Buchhorststr. 13 | 31860 Emmerthal

USt. Nr. 22/129/10953 | USt.-ID 60 634 821 756

**Comment by miguelsimoni** [comment]
Hi @Lego2012 

I think now images on landscape looks better.
Thanks!

PD: About hamburger, I'm not able to test this on an iPhone but with Chrome Developer Tools and it seems it's working for all devices.
