### ISSUE TITLE
Deployment in Netlify

### ISSUE THREAD

**Issue by TiagoVentura** [miguelsimoni/hugo-initio#22]
Hi, 

I am using your Hugo theme to my website using the R package blogdown. I am deploying the website using netlify. However, netlify asks for a folder called public to deploy the website, and I don't get this folder after building the website via blogdown. Is it something with the R package or some other issues I am not paying close attention? I tried to deploy using the folder docs, the deployment works, but the website is not fully working.

Thanks!

**Comment by miguelsimoni** [comment]
Hi @TiagoVentura,

I'm not familiarized with blogdown but for Hugo you just have to check the property `publishDir` on your `config.toml` and be sure it's set to `"public"`.

Regards,
MS
