### ISSUE TITLE
How to change the icon.

### ISSUE THREAD

**Issue by liulu112601** [miguelsimoni/hugo-initio#27]
I want to change the icon, while I did not find its source.
For example, I'm using icon=fa-google-plus-square, while how to use another one that this hugo-initio does not have?, such as fa-google-scholar in https://github.com/gcushen/hugo-academic

**Comment by miguelsimoni** [comment]
Hi @liulu112601,

First of all, sorry for the laaate reply.

You can use any icon available in https://fontawesome.com/icons. Maybe, the `fas fa-graduation-cap` would be the one you're looking for ([see it here](https://fontawesome.com/icons/graduation-cap?style=solid))

(I don't know if is useful at this moment, but I don't want to let this question without an answer).
