### ISSUE TITLE
Read more in Services section

### ISSUE THREAD

**Issue by skyfaller** [miguelsimoni/hugo-initio#3]
Is there any way to make the front page display a summary of e.g. service1.md, so that if you click on "read more" it takes you to a full version of the page? I tried breaking the page up with `<!--more-->` and that had no effect, it still displays the full text both on the front page and if you click "read more".

**Comment by miguelsimoni** [comment]
Hi @skyfaller 
You're right. Services template had showing Content always. Now it's showing Summary, so the  mark works.
Thanks!
