### ISSUE TITLE
use valid HTML instead of invalid "parallax-speed" attribute

### ISSUE THREAD

**Issue by skyfaller** [miguelsimoni/hugo-initio#32]
The attribute `parallax-speed` is not valid HTML. It [appears in the header.html partial](https://github.com/miguelsimoni/hugo-initio/blob/6099c6109436b2fcaaf9a30e4c3e7d699450e773/layouts/partials/header.html#L32) and is [called by template.js](https://github.com/miguelsimoni/hugo-initio/blob/7b62642cbf14d367e91e2250afe309932b4f6dbc/static/js/template.js#L25).

[Data attributes](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) seem like a better option for producing valid HTML.

**Comment by miguelsimoni** [comment]
Fixed.
Thanks for the observation!
