### ISSUE TITLE
Updating theme for newer hugo versions

### ISSUE THREAD

**Issue by drmowinckels** [miguelsimoni/hugo-initio#34]
Hi.

This theme is so amazing, but is a little out of date with respect to current and future hugo practices. 
Any eta on when you'd get to a theme update.

I'm in particular refering to incorporating the (base template)[https://gohugo.io/templates/base/#define-the-base-template] system, (page bundling)[https://gohugo.io/content-management/page-bundles/], and changing `.Page.URL` with `.Permalink` or `.RelPermalink`

Thanks.

**Comment by maklaskarlos** [comment]
Hi, could it be the reason why my site (https://github.com/maklaskarlos/karlosdatablog) is not getting built anymore? I have also an issue when deploying my site (Netlify): 
"build.command" failed
Command failed with exit code 255: hugo
In Build command from Netlify app: hugo
Rstudio --> 4.0.0
blogdown::hugo_version() --> ‘0.78.2’

**Comment by drmowinckels** [comment]
This does not look like an error I would expect because of the lack of hugo blocking.

**Comment by maklaskarlos** [comment]
thank you. I decided to change the theme. A bit more work though.
