### ISSUE TITLE
Updates to README and config.toml of exampleSite

### ISSUE THREAD

**Issue by richtong** [miguelsimoni/hugo-initio#37]
Thanks so much for your hard work on this site and conversion. I finally got it to work after a day. I'm a total hugo noob, I did find a few issues and wonder if you want a pull request:

1. Using the exampleSite is a bit tricky, the config.toml should have a baseurl of "/" right now it is hard coded to localhost so won't work for real deployments
2. The config.toml also defaults to a publish site of docs which isn't standard, so I changed and documented it.
3. I added some more to the README for noobs about how to customize the template and how to host on Netlify and add netlify CMS. Lmk if you want a PR :-)

**Comment by miguelsimoni** [comment]
Hi @richtong! and thanks for your comment :)

About the PR, yes, please! it's totally welcome.

**Comment by richtong** [comment]
Sounds good. FYI. I could not get this template working with netlify identity. Ugh so many different choices make this so hard. The title banner is over the widget for that and I don’t think I added the JavaScript correctly into the template.

Sent via Superhuman iOS ( https://sprh.mn/?vip=rich@tongfamily.com )

**Comment by richtong** [comment]
It would be great to know what setup ur using that works and document it. What headless CMS, what Hoster for noobs. And add instructions for that at least as a starting point. And also how to modify it. What’s your reco and I’ll add to the README.

Sent via Superhuman iOS ( https://sprh.mn/?vip=rich@tongfamily.com )

**Comment by miguelsimoni** [comment]
Hi @richtong! (Sorry for the late response on this)

I just want to let you know that the _baseURL_ was changed to `/` again and the `publishDir=docs` customization was removed so the `publishDir` param is set to the default again (`public`).

About Netlify customization, I didn't publish this particular site on that platform but on GitHub pages, that is one of the reasons the publish directory was set to docs. Also, I´m probably missing some Hugo features for Netlify on this template.

I also update some information on the README file.

Thanks again! :)
