### ISSUE TITLE
How to get rid of test widget in footer

### ISSUE THREAD

**Issue by rayjohnson** [miguelsimoni/hugo-initio#4]
I'm brand new to Hugo and this is the first template I started messing with.  So forgive me if I'm asking something stupid.  

I'm trying to get rid of the text widget in the footer.  Is there a param that turns that on/off?  Same for the FORM WIDGET.

Also, how do I replace the images?

**Comment by murraycolin** [comment]
I would remove the following in `./layouts/partials/footer.html`
```
			<div class="col-md-3 widget">
				<h3 class="widget-title">Text widget</h3>
				<div class="widget-body">
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, nihil natus explicabo ipsum quia iste aliquid repellat eveniet velit ipsa sunt libero sed aperiam id soluta officia asperiores adipisci maxime!</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, nihil natus explicabo ipsum quia iste aliquid repellat eveniet velit ipsa sunt libero sed aperiam id soluta officia asperiores adipisci maxime!</p>
				</div>
			</div>
```
And I would increase the size of another widget to compensate
E.G. `<div class="col-md-3 widget">` to `<div class="col-md-6 widget">`

Existing images are in `./static/images/`.

**Comment by miguelsimoni** [comment]
Done

**Comment by miguelsimoni** [comment]
Done
