### ISSUE TITLE
Mobile version responsiveness issue

### ISSUE THREAD

**Issue by yonkov** [miguelsimoni/hugo-initio#9]
When i checked the theme on my samsung galaxy s5 neo, i noticed that there is some empty space on the right side of the screen. Please check and let me know whether you can fix this.

**Comment by murraycolin** [comment]
I created a pull request for this here: https://github.com/miguelsimoni/hugo-initio/pull/10

**Comment by miguelsimoni** [comment]
Done
Thanks @murraycolin
